# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db982d0059465d42a13daf2c9470d6d8776bf28a7f27bc3e4020820e978a8a9cadc394fe3c8fd644ae971153bbec5db6542222beddaee8d55939da85646455ef

test:
  secret_key_base: a644bbdb16ae778f0f4e14853174f5543c47f31154e98ad03514ce33f9fe74312bcb97e1ab6649acda37cb81626f436af692792c81f0ba243e4d451c1cfbee46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
